version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_CLASS_CONNECT_CLIENT_SECRETE=${NEXT_CLASS_CONNECT_CLIENT_SECRETE}
        - NEXT_CLASS_CONNECT_CLIENT_ID=${NEXT_CLASS_CONNECT_CLIENT_ID}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_CLASS_CONNECT_CLIENT_SECRETE=${NEXT_CLASS_CONNECT_CLIENT_SECRETE}
      - NEXT_CLASS_CONNECT_CLIENT_ID=${NEXT_CLASS_CONNECT_CLIENT_ID}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .env:/app/.env
