# Generated by Django 5.1.4 on 2025-03-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['created_at'], 'verbose_name': 'Message'},
        ),
    ]
