# Generated by Django 5.1.4 on 2025-03-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_messages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.messages'),
        ),
    ]
