apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_USERNAME: Z3Vlc3Q= # Base64 encoded value of "classconnect"
  RABBITMQ_PASSWORD: Z3Vlc3Q= # Base64 encoded value of "classconnect"
