# Generated by Django 5.1.4 on 2025-04-22 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streamings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconferencesession',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoconferencesession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
