# Generated by Django 5.1.4 on 2025-02-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
