# Generated by Django 5.1.4 on 2025-03-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_schoolyear_is_active_and_more'),
        ('streamings', '0003_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconferencesession',
            name='teacher_student_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_course', to='courses.teacherstudentenrollment'),
        ),
    ]
