# Generated by Django 5.1.4 on 2025-03-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0004_videoconferencesession_teacher_student_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionParticipant',
        ),
    ]
