# Generated by Django 5.1.4 on 2025-04-02 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamings', '0005_delete_sessionparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconferencesession',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='videoconferencesession',
            name='teacher_student_enrollment',
        ),
        migrations.AddField(
            model_name='videoconferencesession',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoconferencesession',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
