# Generated by Django 5.1.4 on 2025-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreference',
            name='provider',
            field=models.CharField(default='campay', max_length=50),
        ),
    ]
