# Generated by Django 5.1.4 on 2025-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentreference_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='campay', max_length=50),
        ),
    ]
