# Generated by Django 5.1.4 on 2025-03-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
