# Generated by Django 5.1.4 on 2025-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
