# Generated by Django 5.1.4 on 2025-02-15 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscriptionplan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='app_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='operator_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='operator_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.subscription'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('app_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('XAF', 'CFA Franc')], default='XAF', max_length=3)),
                ('operator', models.CharField(choices=[('MTN', 'MTN Money'), ('ORANGE', 'Orange Money')], max_length=10)),
                ('endpoint', models.CharField(choices=[('collect', 'Collection'), ('withdraw', 'Withdrawal')], max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('operator_reference', models.CharField(max_length=50)),
                ('external_reference', models.UUIDField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_user', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='payments_tr_phone_n_e90854_idx'), models.Index(fields=['operator'], name='payments_tr_operato_493a99_idx'), models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'), models.Index(fields=['endpoint'], name='payments_tr_endpoin_f7598d_idx'), models.Index(fields=['created_at'], name='payments_tr_created_02ae92_idx')],
            },
        ),
    ]
