# Generated by Django 5.1.4 on 2025-02-26 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedeclaration',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_declarations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseofferingaction',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='courseofferingaction',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together={('start_year', 'end_year')},
        ),
        migrations.AddField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.class'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='teacherstudentenrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='teacherstudentenrollment',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.schoolyear'),
        ),
        migrations.AddField(
            model_name='teacherstudentenrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursedeclaration',
            name='teacher_student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='courses.teacherstudentenrollment'),
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='abstractresource',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_resources', to='courses.topic'),
        ),
        migrations.AddField(
            model_name='useravailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytimeslot',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_slots', to='courses.useravailability'),
        ),
        migrations.AddField(
            model_name='userclass',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
        migrations.AddField(
            model_name='userclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.abstractresource'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherstudentenrollment',
            index=models.Index(fields=['teacher', 'school_year'], name='courses_tea_teacher_7a799d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudentenrollment',
            unique_together={('teacher', 'offer', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='useravailability',
            unique_together={('user', 'user_type')},
        ),
        migrations.AlterUniqueTogether(
            name='dailytimeslot',
            unique_together={('availability', 'day', 'time_slot')},
        ),
    ]
