# Generated by Django 5.1.4 on 2025-02-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-start_year']},
        ),
    ]
