# Generated by Django 5.1.4 on 2025-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('COLLEGE', 'College'), ('LYCEE', 'Lycée'), ('UNIVERSITY', 'Université'), ('PROFESSIONAL', 'Professionnel')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FR', 'Francophone'), ('EN', 'Anglophone')], max_length=2, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('scientifique', 'Scientifique'), ('litteraire', 'Littéraire')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='level',
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.RemoveField(
            model_name='class',
            name='speciality',
        ),
        migrations.AddField(
            model_name='class',
            name='variant',
            field=models.CharField(blank=True, help_text="Optional variant label, e.g. 'A', 'C', 'A4'.", max_length=50),
        ),
        migrations.CreateModel(
            name='LevelClassDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_definitions', to='courses.educationlevel')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_definitions', to='courses.speciality')),
            ],
            options={
                'unique_together': {('education_level', 'name', 'speciality')},
            },
        ),
        migrations.AddField(
            model_name='class',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='courses.levelclassdefinition'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_levels', to='courses.section'),
        ),
    ]
