# Generated by Django 5.1.4 on 2025-02-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_schoolyear_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseofferingaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
