# Generated by Django 5.1.4 on 2025-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_educationlevel_section_speciality_remove_class_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='code',
            field=models.CharField(choices=[('COLLEGE', 'College'), ('LYCEE', 'Lycée'), ('UNIVERSITY', 'Université'), ('PROFESSIONAL', 'Professionnel')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='educationlevel',
            unique_together={('code', 'section')},
        ),
    ]
