# Generated by Django 5.1.4 on 2025-01-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_abstractresource_slug_quizresource_attempts_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresource',
            name='video_url',
        ),
    ]
