# Generated by Django 5.1.4 on 2025-03-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseofferingaction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.schoolyear'),
        ),
    ]
