# Generated by Django 5.1.4 on 2025-05-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_educationlevel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudentenrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_student_enrollments', to='courses.courseoffering'),
        ),
    ]
