# Generated by Django 5.1.4 on 2025-03-21 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_userclass_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseofferingaction',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseofferingaction_set', to='courses.courseoffering'),
        ),
    ]
