# Generated by Django 5.1.4 on 2025-03-22 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseofferingaction_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
