# Generated by Django 5.1.4 on 2025-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('FRANCOPHONE', 'Francophone'), ('ANGLOPHONE', 'Anglophone')], default='FRANCOPHONE', max_length=20),
        ),
    ]
