# Generated by Django 5.1.4 on 2025-03-30 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseoffering_created_at_courseoffering_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursedeclaration',
            name='declaration_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Declaration Date'),
        ),
        migrations.AlterField(
            model_name='coursedeclaration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
    ]
