# Generated by Django 5.1.4 on 2025-02-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresource',
            name='attempts_allowed',
        ),
        migrations.RemoveField(
            model_name='quizresource',
            name='partial_credit',
        ),
        migrations.RemoveField(
            model_name='quizresource',
            name='show_explanation',
        ),
        migrations.RemoveField(
            model_name='quizresource',
            name='total_questions',
        ),
    ]
