# Generated by Django 5.1.4 on 2025-04-10 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_schoolyear_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedeclaration',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_declarations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursedeclaration',
            name='payment_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedeclaration',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='coursedeclaration',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='declarations/'),
        ),
    ]
