# Generated by Django 5.1.4 on 2025-02-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_questionresponse_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='speciality',
            field=models.CharField(blank=True, choices=[('scientifique', 'Scientifique'), ('litteraire', 'Litteraire')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('COLLEGE', 'College'), ('LYCEE', 'Lycée'), ('UNIVERSITY', 'Université'), ('PROFESSIONAL', 'Professionnel')], max_length=20),
        ),
    ]
