version: '3.8'
networks:
  e_learning_network:
    driver: bridge
services:
  api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: /start.sh
    container_name: classconnect_api
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # For static files
    ports:
      - "8001:8001"
    env_file:
      - .envs/.prod/django
      - .envs/.prod/backblaze
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - e_learning_network

  db:
    image: postgres:alpine3.20
    restart: unless-stopped
    container_name: classconnect_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.prod/postgres
    ports:
      - "5432:5432"
    networks:
      - e_learning_network

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    hostname: rabbitmq
    container_name: classconnect_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .envs/.prod/rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - e_learning_network

  redis:
    image: redis:7.4
    container_name: classconnect_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - e_learning_network

volumes:
  postgres_data:
  rabbitmq_data:
  static_volume:  # New volume for static files
  redis_data: