networks:
  e_learning_network:
    driver: bridge
services:
  api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: /start.sh
    container_name: classconnect_api
    restart: unless-stopped
    volumes:
      - .:/app
      - monolythic_static_volume:/app/staticfiles # For static files
    ports:
      - "8000:8000" 
    env_file:
      - .envs/.prod/django
      - .envs/.prod/backblaze
    depends_on:
      # - db
      - rabbitmq
      - redis
    network_mode: "host"
  # db:
  #   image: postgres:14-alpine3.20
  #   restart: unless-stopped
  #   container_name: classconnect_db
  #   volumes:
  #     - monolythic_postgres_data:/var/lib/postgresql/data
  #     - ./docker/prod/db-scripts:/docker-entrypoint-initdb.d
  #   env_file:
  #     - .envs/.prod/postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - e_learning_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  
  # Database backup service
  # db-backup:
  #   image: prodrigestivill/postgres-backup-local:14-alpine
  #   container_name: classconnect_db_backup
  #   restart: unless-stopped
  #   volumes:
  #     - monolythic_postgres_backups:/backups
  #   env_file:
  #     - .envs/.prod/postgres
  #   environment:
  #     - POSTGRES_HOST=db
  #     - SCHEDULE=@daily
  #     - BACKUP_KEEP_DAYS=7     # Keep backups for 7 days
  #     - BACKUP_KEEP_WEEKS=4    # Keep weekly backups for 4 weeks
  #     - BACKUP_KEEP_MONTHS=6   # Keep monthly backups for 6 months
  #     - HEALTHCHECK_PORT=8080  # Port for the health check web server
  #   depends_on:
  #     - db
  #   networks:
  #     - e_learning_network
  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    hostname: rabbitmq
    container_name: classconnect_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .envs/.prod/rabbitmq
    volumes:
      - monolythic_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - e_learning_network
  redis:
    image: redis:7.4
    container_name: classconnect_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - monolythic_redis_data:/data
    networks:
      - e_learning_network
  celery_worker:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: classconnect_celery_worker
    command: celery -A backend worker --loglevel=info
    restart: unless-stopped
    env_file:
      - .envs/.prod/django
      - .envs/.prod/backblaze
    depends_on:
      - api
      - rabbitmq
      - redis
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
    network_mode: "host"
  celery_beat:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: classconnect_celery_beat
    command: celery -A backend beat --loglevel=info
    restart: unless-stopped
    env_file:
      - .envs/.prod/django
      - .envs/.prod/backblaze
    depends_on:
      - api
      - celery_worker
      - rabbitmq
      - redis
    entrypoint: /entrypoint.sh
    volumes:
      - .:/app
    network_mode: "host"
volumes:
  # monolythic_postgres_data:
  #   name: monolythic_postgres_data
  #   labels:
  #     - "keep=true"
  monolythic_rabbitmq_data:
    labels:
      - "keep=true"
  monolythic_static_volume:
    labels:
      - "keep=true"
  monolythic_redis_data:
    labels:
      - "keep=true"
  # monolythic_postgres_backups:
  #   name: monolythic_postgres_backups
  #   labels:
  #     - "keep=true"
