version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - PYTHONUNBUFFERED=1
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EMAIL_HOST='smtp.gmail.com'
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=587
      - POSTGRES_DB=e_learning
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

    depends_on:
      - db
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:13
    container_name: user_service_db
    environment:
      POSTGRES_DB: e_learning
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
