# Generated by Django 5.1.4 on 2025-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_educationlevel_section_speciality_remove_class_level_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lycee_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university_year',
        ),
        migrations.AddField(
            model_name='user',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.class'),
        ),
    ]
