# Generated by Django 5.1.4 on 2025-02-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_class_grade_user_enterprise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lycee_speciality',
            field=models.CharField(blank=True, choices=[('scientifique', 'scientifique'), ('litteraire', 'litteraire')], max_length=255, null=True),
        ),
    ]
