# Generated by Django 5.1.4 on 2025-02-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('UNIVERSITY', 'Université'), ('PROFESSIONAL', 'Professionnel')], max_length=20, null=True),
        ),
    ]
