# Generated by Django 5.1.4 on 2025-05-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_college_class_remove_user_lycee_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lycee_speciality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university_level',
        ),
    ]
