# Generated by Django 5.1.4 on 2025-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_lycee_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='college_class',
            field=models.CharField(blank=True, choices=[('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème')], help_text='Class for college students', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('UNIVERSITY', 'Université'), ('PROFESSIONAL', 'Professionnel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='lycee_class',
            field=models.CharField(blank=True, choices=[('2nde', '2nde'), ('1ere', '1ère'), ('terminale', 'Terminale')], help_text='Class for lycee students', max_length=20, null=True),
        ),
    ]
