# Generated by Django 5.1.4 on 2025-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_lycee_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education_level',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('PROFESSIONAL', 'Professional')], default='STUDENT', max_length=20),
        ),
    ]
