name: CI/CD auth-app
on:
  push:
    branches:
      - main
jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend using SSH (Main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/class-connect/backend/monolythic
            git pull --all
            docker compose -f prod.yml up --build -d