
name: CI/CD auth-app
on:
  push:
    branches:
      - main
jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend using SSH (Main)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/class-connect/backend/monolythic
            git pull --all
            docker compose -f prod.yml up --build -d
